// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: offersrpc.proto

package offersrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendOnionMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The pubkey of the peer to send the message to. As currently implemented
	// the server will make an ad-hoc connection to the peer (if not already
	// connected) to deliver the message.
	//
	// NB: This will reveal your IP address if you are not running tor. In
	// future iterations this API will find a route to the peer and send the
	// message along a blinded path, protecting sender identity.
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *SendOnionMessageRequest) Reset() {
	*x = SendOnionMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offersrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOnionMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOnionMessageRequest) ProtoMessage() {}

func (x *SendOnionMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOnionMessageRequest.ProtoReflect.Descriptor instead.
func (*SendOnionMessageRequest) Descriptor() ([]byte, []int) {
	return file_offersrpc_proto_rawDescGZIP(), []int{0}
}

func (x *SendOnionMessageRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type SendOnionMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendOnionMessageResponse) Reset() {
	*x = SendOnionMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offersrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOnionMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOnionMessageResponse) ProtoMessage() {}

func (x *SendOnionMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_offersrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOnionMessageResponse.ProtoReflect.Descriptor instead.
func (*SendOnionMessageResponse) Descriptor() ([]byte, []int) {
	return file_offersrpc_proto_rawDescGZIP(), []int{1}
}

var File_offersrpc_proto protoreflect.FileDescriptor

var file_offersrpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x72, 0x70, 0x63, 0x22, 0x31, 0x0a, 0x17,
	0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x22,
	0x1a, 0x0a, 0x18, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x65, 0x0a, 0x06, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x73, 0x12, 0x5b, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x69,
	0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x2e, 0x6f, 0x66, 0x66, 0x65,
	0x72, 0x73, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e, 0x69, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x6e,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x61, 0x72, 0x6c, 0x61, 0x6b, 0x63, 0x2f, 0x62, 0x6f, 0x6c, 0x74, 0x6e, 0x64, 0x2f,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_offersrpc_proto_rawDescOnce sync.Once
	file_offersrpc_proto_rawDescData = file_offersrpc_proto_rawDesc
)

func file_offersrpc_proto_rawDescGZIP() []byte {
	file_offersrpc_proto_rawDescOnce.Do(func() {
		file_offersrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_offersrpc_proto_rawDescData)
	})
	return file_offersrpc_proto_rawDescData
}

var file_offersrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_offersrpc_proto_goTypes = []interface{}{
	(*SendOnionMessageRequest)(nil),  // 0: offersrpc.SendOnionMessageRequest
	(*SendOnionMessageResponse)(nil), // 1: offersrpc.SendOnionMessageResponse
}
var file_offersrpc_proto_depIdxs = []int32{
	0, // 0: offersrpc.Offers.SendOnionMessage:input_type -> offersrpc.SendOnionMessageRequest
	1, // 1: offersrpc.Offers.SendOnionMessage:output_type -> offersrpc.SendOnionMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_offersrpc_proto_init() }
func file_offersrpc_proto_init() {
	if File_offersrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_offersrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOnionMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offersrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOnionMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_offersrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_offersrpc_proto_goTypes,
		DependencyIndexes: file_offersrpc_proto_depIdxs,
		MessageInfos:      file_offersrpc_proto_msgTypes,
	}.Build()
	File_offersrpc_proto = out.File
	file_offersrpc_proto_rawDesc = nil
	file_offersrpc_proto_goTypes = nil
	file_offersrpc_proto_depIdxs = nil
}
